### ISSUE TITLE
config/is09-13/IS13_ComParE_lld.conf cannot find

### ISSUE THREAD

**Issue by Morpheus0319** [audeering/opensmile#14]
The configuration file config/is09-13/IS13_ComParE_lld.conf cannot find.

**Comment by chausner-audeering** [comment]
Thanks for reporting this issue! I see we are mentioning `config/is09-13/IS13_ComParE_lld.conf` in the documentation but this file has not been existing at least since version 2.3. We need to fix that.

For extracting low-level descriptors, you can just use `config/is09-13/IS13_ComParE.conf` with the `-lldcsvoutput`, `-lldhtkoutput` or `-lldarffoutput` command-line options.

**Comment by chausner-audeering** [comment]
The part in the documentation that previously mentioned this non-existing file has been updated in the latest release, so I am closing this.
