### ISSUE TITLE
Accept a pcm data, return to extract feature data

### ISSUE THREAD

**Issue by srdfjy** [audeering/opensmile#26]
Hi，We know that when executing SMILExtract, you need to specify an input file and output a file. E.g:
`SMILExtract -C config/emobase/emobase2010.conf -I ./1.WAV -O ./1.arff`

I want to input a pcm data and return the extracted feature data. Is this possible?

**Comment by chausner-audeering** [comment]
openSMILE comes with SMILEapi which is a C API allowing to embed openSMILE into other applications. Instead of `cWaveSource` and `cArffSink` components for file reading/writing, you would then use special components for reading/writing data in memory: `cExternalDataSource`, `cExternalAudioDataSource` and `cExternalDataSink`.

You can find more information on this in the openSMILE documentation in the "SMILEapi" section.

**Comment by srdfjy** [comment]
@chausner-audeering thanks
