### ISSUE TITLE
Extract emotions from speech

### ISSUE THREAD

**Issue by dstefa02** [audeering/opensmile#45]
Hello,

Is it possible to extract emotions from speech using opensmile (e.g. happy, anger, etc)? In the main page, it states that this toolkit can be also used for emotion recognition, but it is not clear whether this functionality is available (e.g. pretrained model) and how this can be achieved. 

Any help or advise would be greatly helpful.
Thanks

**Comment by chausner-audeering** [comment]
openSMILE is purely an audio feature extractor and does not come with any pre-trained models. In order to use openSMILE for emotion recognition, a model needs to be trained first on the output of openSMILE and some training set.

We (audEERING) do offer [devAIce](https://www.audeering.com/products/devaice/) as a commercial solution shipping with pre-trained models for emotion recognition and more.
